language: java
sudo: false
dist: trusty
jdk:
  - openjdk11

matrix:
  fast_finish: true

before_install:  
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
 - mvn install -B -V
 - mvn javadoc:jar
 - mvn javadoc:test-aggregate
