sudo: false
language: java
sudo: false
dist: trusty
jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11

matrix:
  allow_failures: 
    - jdk: openjdk11
  fast_finish: true

before_install:  
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

script:
 - mvn install -B -V
 - mvn javadoc:jar
 - mvn javadoc:test-aggregate

notifications:
  irc: "irc.freenode.org#fcrepo"
  email:
      - fedora-tech@googlegroups.com
